version: '3.7'
services:
  mariadb:
    restart: always
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=root
    volumes:
     - ./database:/var/lib/mysql
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '81:80'
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
  assent:
    restart: always
    container_name: assent
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/app/
    ports:
      - '80:80'
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=official_assent
      - DB_USERNAME=root
      - DB_PASSWORD=root
